setwd("~/Downloads")
library(sqldf)
png("plot3.png",height = 480,width= 480)
filtered$DateTime <- as.POSIXct(paste(filtered$Date,filtered$Time), format="%d/%m/%Y %H:%M:%S") 
plot(filtered$DateTime,filtered$Sub_metering_1,type="n",xlab="",ylab="Energy sub metering")
lines(filtered$DateTime,filtered$Sub_metering_1,col="black")
lines(filtered$DateTime,filtered$Sub_metering_2,col="red")
lines(filtered$DateTime,filtered$Sub_metering_3,col="blue")
legend("topright",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1,1))
dev.off()
